# Use official Node.js image
FROM node:18-alpine


# Common tools
RUN apk add --no-cache curl

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install web-vitals
RUN npm install

# Copy all source code
COPY . .

# Expose the port
EXPOSE 3001

# Start the app
CMD ["npm", "start"]
