server:
  port: 8081

spring:
  application:
    name: api-gateway-service

  cloud:
    gateway:
      routes:
        # ================= USER SERVICE =================
        - id: user-management-service
          uri: lb://user-management-service
          predicates:
            - Path=/api/users/**,/api/auth/**
          filters:
            - StripPrefix=1
            - JwtAuthenticationFilter
        # ================= PRODUCT SERVICE =================
        - id: product-catalog-service
          uri: lb://product-catalog-service
          predicates:
            - Path=/api/products/**
          filters:
            - JwtAuthenticationFilter
        # ================= ORDER SERVICE =================
        - id: order-management-service
          uri: lb://order-management-service
          predicates:
            - Path=/api/orders/**,/api/orders
          filters:
            - JwtAuthenticationFilter
        # ================= PAYMENT SERVICE =================
        - id: payment-management-service
          uri: lb://payment-management-service
          predicates:
            - Path=/api/payments/**
          filters:
            - JwtAuthenticationFilter
        # ================= INVENTORY SERVICE =================
        - id: inventory-management-service
          uri: lb://inventory-management-service
          predicates:
            - Path=/api/inventory/**
          filters:
            - JwtAuthenticationFilter
        # ====================================================
        # ================= SWAGGER ROUTES ===================
        # ====================================================
        - id: user-swagger
          uri: lb://user-management-service
          predicates:
            - Path=/user/v3/api-docs
        - id: product-swagger
          uri: lb://product-catalog-service
          predicates:
            - Path=/product/v3/api-docs
        - id: order-swagger
          uri: lb://order-management-service
          predicates:
            - Path=/order/v3/api-docs
        - id: payment-swagger
          uri: lb://payment-management-service
          predicates:
            - Path=/payment/v3/api-docs
        - id: inventory-swagger
          uri: lb://inventory-management-service
          predicates:
            - Path=/inventory/v3/api-docs
# =========================================================
# ================= SPRINGDOC CONFIG ======================
# =========================================================
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: User Management Service
        url: /user/v3/api-docs
      - name: Product Catalog Service
        url: /product/v3/api-docs
      - name: Order Management Service
        url: /order/v3/api-docs
      - name: Payment Management Service
        url: /payment/v3/api-docs
      - name: Inventory Management Service
        url: /inventory/v3/api-docs
