server:
  port: 8081

spring:
  application:
    name: api-gateway-service

springdoc:
  swagger-ui:
    use-root-path: true
    path: /swagger-ui/index.html
    urls:
      - name: User Service
        url: /api/user/v3/api-docs
