server:
  port: 8081

spring:
  application:
    name: api-gateway-service

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    persistAuthorization: true
    urls:
      - name: User Service
        url: /api/user/v3/api-docs