server:
  port: 8082

spring:
  application:
    name: user-management-service

springdoc:
  api-docs:
    path: /api/user/v3/api-docs
  swagger-ui:
    path: /api/user/swagger-ui/index.html

encryption:
  secret-key: ${ENCRYPTION_SECRET_KEY:u14kB@(%AEE6kKSh}