CREATE TABLE IF NOT EXISTS public.password_reset_tokens
(
    id         bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token      varchar(64)  NOT NULL UNIQUE,
    user_id    bigint       NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
    expires_at timestamp    NOT NULL,
    used       boolean      NOT NULL DEFAULT false,
    created_at timestamp    NOT NULL DEFAULT current_timestamp
);

CREATE INDEX idx_password_reset_tokens_token ON public.password_reset_tokens (token);
CREATE INDEX idx_password_reset_tokens_user_id ON public.password_reset_tokens (user_id);
CREATE INDEX idx_password_reset_tokens_expires_at ON public.password_reset_tokens (expires_at);
