-- Shopping cart: one cart per user (user_id from gateway), cart_items reference product_id
CREATE TABLE IF NOT EXISTS public.carts
(
    id         bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    varchar(255) NOT NULL,
    created_at timestamp(6) DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_cart_user UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.cart_items
(
    id         bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id    bigint NOT NULL,
    product_id bigint NOT NULL,
    quantity   int   NOT NULL DEFAULT 1,
    created_at timestamp(6) DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cart_items_cart FOREIGN KEY (cart_id) REFERENCES public.carts (id) ON DELETE CASCADE,
    CONSTRAINT fk_cart_items_product FOREIGN KEY (product_id) REFERENCES public.products (id) ON DELETE CASCADE,
    CONSTRAINT uk_cart_product UNIQUE (cart_id, product_id),
    CONSTRAINT chk_quantity_positive CHECK (quantity > 0)
);

CREATE INDEX IF NOT EXISTS idx_cart_items_cart_id ON public.cart_items (cart_id);
CREATE INDEX IF NOT EXISTS idx_carts_user_id ON public.carts (user_id);
