-- Wishlist: user saves products (user_id from gateway, product_id from products)
CREATE TABLE IF NOT EXISTS public.wishlist
(
    id         bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    varchar(255) NOT NULL,
    product_id bigint       NOT NULL,
    created_at timestamp(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_wishlist_product FOREIGN KEY (product_id) REFERENCES public.products (id) ON DELETE CASCADE,
    CONSTRAINT uk_wishlist_user_product UNIQUE (user_id, product_id)
);

CREATE INDEX IF NOT EXISTS idx_wishlist_user_id ON public.wishlist (user_id);
CREATE INDEX IF NOT EXISTS idx_wishlist_product_id ON public.wishlist (product_id);
