-- Product reviews and ratings (1-5)
CREATE TABLE IF NOT EXISTS public.product_reviews
(
    id         bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id bigint       NOT NULL,
    user_id    varchar(255) NOT NULL,
    rating     int          NOT NULL,
    comment    text,
    created_at timestamp(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_review_product FOREIGN KEY (product_id) REFERENCES public.products (id) ON DELETE CASCADE,
    CONSTRAINT chk_rating_range CHECK (rating >= 1 AND rating <= 5),
    CONSTRAINT uk_review_user_product UNIQUE (user_id, product_id)
);

CREATE INDEX IF NOT EXISTS idx_reviews_product_id ON public.product_reviews (product_id);
CREATE INDEX IF NOT EXISTS idx_reviews_user_id ON public.product_reviews (user_id);
