-- Coupons / discount codes
CREATE TABLE IF NOT EXISTS public.coupons
(
    id               bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code             varchar(50)   NOT NULL,
    type             varchar(20)   NOT NULL,
    value            numeric(10, 2) NOT NULL,
    min_order_amount numeric(10, 2) DEFAULT 0,
    valid_from       timestamp(6),
    valid_to         timestamp(6),
    max_uses         int          DEFAULT NULL,
    used_count       int          DEFAULT 0,
    CONSTRAINT uk_coupon_code UNIQUE (code),
    CONSTRAINT chk_coupon_type CHECK (type IN ('PERCENT', 'FIXED')),
    CONSTRAINT chk_value_positive CHECK (value > 0)
);

CREATE INDEX IF NOT EXISTS idx_coupons_code ON public.coupons (code);
