-- Shipping options for checkout
CREATE TABLE IF NOT EXISTS public.shipping_options
(
    id             bigint        NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           varchar(100)  NOT NULL,
    cost           numeric(10, 2) NOT NULL DEFAULT 0,
    estimated_days int,
    is_default     boolean       DEFAULT false
);

INSERT INTO public.shipping_options (name, cost, estimated_days, is_default)
VALUES ('Standard', 5.00, 5, true),
       ('Express', 12.00, 2, false);
