-- In-app notifications for users
CREATE TABLE IF NOT EXISTS public.user_notifications
(
    id         bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    varchar(255) NOT NULL,
    title      varchar(255) NOT NULL,
    message    text,
    read       boolean      DEFAULT false,
    created_at timestamp(6) DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON public.user_notifications (user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_read ON public.user_notifications (user_id, read);
