CREATE TABLE IF NOT EXISTS public.orders
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    status character varying(255) COLLATE pg_catalog."default",
    total_amount numeric(38,2),
    user_id character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT orders_pkey PRIMARY KEY (id),
    CONSTRAINT orders_status_check CHECK (status::text = ANY (ARRAY['CREATED'::character varying, 'PAID'::character varying, 'CANCELLED'::character varying, 'SHIPPED'::character varying]::text[]))
)